---

server:
  port: 9000
eureka:
  instance:
    hostname: eureka-center-1
    appname: eureka-server
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka-center-2:9001/eureka/
      defaultZone: http://eureka-center-1:9000/eureka/
spring:
  application:
    name: eureka-server
  profiles: center1

---
server:
  port: 9001
eureka:
  instance:
    hostname: eureka-center-2
    appname: eureka-server
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-center-1:9000/eureka/
spring:
  application:
    name: eureka-server
  profiles: center2