
server:
  port: 9000
eureka:
  instance:
    hostname: eureka-center-1
    appname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-center-2:9001/eureka/
spring:
  application:
    name: eureka-server