server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka-center-1:9000/eureka/
  #      ,http://eureka-center-1:9001/eureka/
  instance:
    appname: shop-product-server
